brew install --cask chromium
brew install --cask clocker
brew install --cask drawio
brew install --cask bruno
brew install --cask iterm2
brew install --cask keepingyouawake
brew install --cask microsoft-edge
brew install --cask visual-studio-code
brew install --cask zoom
brew install --cask trex
